export type Units = "Imperial" | "Metric";
export type WeatherGraphics =
  | "US_SEVERE_WEATHER_RISK"
  | "US_FORECAST_HIGH_TEMPS"
  | "US_FORECAST_LOW_TEMPS"
  | "NA_FORECAST_HIGH_TEMPS"
  | "NA_FORECAST_LOW_TEMPS"
  | "US_SURFACE_WEATHER_FORECAST"
  | "NA_SURFACE_WEATHER_FORECAST";
